services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        ports:
            - "8080:80"
        environment:
            SERVER_NAME: ":80"
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: app_db
            DB_USERNAME: app_user
            DB_PASSWORD: secret
        volumes:
            - .:/app
        depends_on:
            - db

    db:
        image: mysql:8.0
        container_name: db
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: app_db
            MYSQL_USER: app_user
            MYSQL_PASSWORD: secret
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
